### ISSUE TITLE
A setter calling another setter generates a StackOverflowError

### ISSUE THREAD

**Issue by sp00m** [playframework/play1#1123]
With Play Framework v1.4.2, I catch a StackOverflowError during the *accessors generation* phase when having a setter calling another setter. For instance, when building:

```java
public boolean flag2;

/** Kept for backward compatibility purposes, defaulted to flag1. */
@Deprecated
public boolean flag1 = flag2;

public void setFlag2(boolean flag2) {
	this.flag1 = flag2;
	this.flag2 = flag2;
}

public void setFlag1(boolean flag1) {
	setFlag2(flag1);
}
```

This generates:

```text
...
Caused by: java.lang.StackOverflowError
	at play.vfs.VirtualFile.exists(VirtualFile.java:99)
	at play.classloading.ApplicationClasses.getJava(ApplicationClasses.java:344)
	at play.classloading.ApplicationClasses.getApplicationClass(ApplicationClasses.java:49)
	at play.classloading.ApplicationClassloader.loadApplicationClass(ApplicationClassloader.java:136)
	at play.classloading.ApplicationClassloader.loadClass(ApplicationClassloader.java:84)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at play.classloading.enhancers.PropertiesEnhancer$FieldAccessor.invokeWriteProperty(PropertiesEnhancer.java:272)
	at play.classloading.enhancers.PropertiesEnhancer$FieldAccessor.invokeWriteProperty(PropertiesEnhancer.java:234)
	at mypackage.MyClass.setFlag2(MyClass.java:xxx)
	at mypackage.MyClass.setFlag1(MyClass.java:xxx)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at play.classloading.enhancers.PropertiesEnhancer$FieldAccessor.invokeWriteProperty(PropertiesEnhancer.java:272)
	at play.classloading.enhancers.PropertiesEnhancer$FieldAccessor.invokeWriteProperty(PropertiesEnhancer.java:234)
	at mypackage.MyClass.setFlag2(MyClass.java:xxx)
	at mypackage.MyClass.setFlag1(MyClass.java:xxx)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at play.classloading.enhancers.PropertiesEnhancer$FieldAccessor.invokeWriteProperty(PropertiesEnhancer.java:272)
	at play.classloading.enhancers.PropertiesEnhancer$FieldAccessor.invokeWriteProperty(PropertiesEnhancer.java:234)
	at mypackage.MyClass.setFlag2(MyClass.java:xxx)
	at mypackage.MyClass.setFlag1(MyClass.java:xxx)
...
```

**Comment by sp00m** [comment]
Wait, this error occurs as well when using the following `setFlag1` setter:

```java
public void setFlag1(boolean flag1) {
	this.flag1 = flag1;
	this.flag2 = flag1;
}
```

So the issue doesn't seem to come from the fact that a setter is calling another setter... Any idea what's happening?

**Comment by asolntsev** [comment]
Hi Christophe!
Yes, this issue is caused by the fact the one setter is calling another
setter, and vice versa.

Everywhere in your code, Play PropertyEnhancer replaces all direct accesses
to fields by setters/getter. So, as a result of play enhancement, your code
is modified to the following:

public void setFlag2(boolean flag2) {
	*this.setFlag1(flag2);*   // calls setFlag, which calls setFlag2
again -> infinite loop
	this.flag2 = flag2;     // play doesn't modify this line because it's
already inside setter
}
public void setFlag1(boolean flag1) {
	setFlag2(flag1);
}


One simple option is to move your class from "app" to "src" folder. In this
case Play will not enhance your class. But you will need to build it and
pack into jar. Probably it's a good idea.

Andrei Solntsev

2017-03-23 22:21 GMT+02:00 Christophe Maillard <notifications@github.com>:

**Comment by asolntsev** [comment]
[image: Встроенное изображение 1]

:)

Andrei Solntsev

2017-03-23 22:49 GMT+02:00 Andrei Solntsev <andrei.solntsev@gmail.com>:

**Comment by sp00m** [comment]
Hey @asolntsev, thanks for your quick answer! Is there any other way to prevent setters generation? What if I modify the visibility of my field from `public` to `private` for example?

**Comment by asolntsev** [comment]
Yes, there is a simple way to disable generation of getters/setters. Just
add the following line to application.conf:

play.propertiesEnhancer.generateAccessors=false


Andrei Solntsev

2017-03-23 23:11 GMT+02:00 Christophe Maillard <notifications@github.com>:

**Comment by sp00m** [comment]
@asolntsev, and for these specific setters only? The code base I'm working on is quite huge, I'm afraid disabling accessors generation globally will create other side issues... Thanks for your precious help!

**Comment by asolntsev** [comment]
As long as I can see from Play code, there are some hacks that you could
try:

1. Make fields flag1 and flag2 *non-public* - probably it's the best
option.
2. Make MyObject class non-public
3. Rename flag1 to FLAG1

Andrei Solntsev

2017-03-23 23:59 GMT+02:00 Christophe Maillard <notifications@github.com>:

**Comment by sp00m** [comment]
Right, I opted for non-public fields, this fixed my issue. Thanks again @asolntsev!
