### ISSUE TITLE
POST Request Body is limited to 8192

### ISSUE THREAD

**Issue by jaesga** [playframework/play1#1163]
Hi,

I have encountered some problems while making POST Request to my Play! application. 
If the body lenght is greater than 8192 the following exception is thrown:

`Oops: IOException
Unexpected error : Unexpected Error, caused by exception IOException: Stream Closed

play.exceptions.UnexpectedException: Unexpected Error
	at play.data.parsing.TextParser.parse(TextParser.java:25)
	at play.mvc.Scope$Params.checkAndParse(Scope.java:380)
	at play.mvc.Scope$Params.all(Scope.java:474)
	at play.mvc.ActionInvoker.getActionMethodArgs(ActionInvoker.java:625)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:450)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:436)
	at play.mvc.ActionInvoker.handleBefores(ActionInvoker.java:299)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:144)
	at Invocation.HTTP Request(Play!)
Caused by: java.io.IOException: Stream Closed
	at java.io.FileInputStream.read0(Native Method)
	at java.io.FileInputStream.read(FileInputStream.java:207)
	at play.data.parsing.TextParser.parse(TextParser.java:18)
	... 8 more
`

I think this is caused because by default the maxChunkSize of `HttpRequestDecoder` from netty is 8192. 

Does it make sense to make this a config value or increase with a higher value?

Regards.

**Comment by asolntsev** [comment]
@jaesga Yes, certainly it could be configurable. 
Can you prepare a pull request for fixing this issue?

**Comment by asolntsev** [comment]
@jaesga Hi! Is the problem still actual? Can we close the issue?

**Comment by xael-fry** [comment]
Yes the problem still exist for long url
