### ISSUE TITLE
Error with JPA query on Play 1.5

### ISSUE THREAD

**Issue by dabeeeenster** [playframework/play1#1196]
My code that was working with 1.4.4 now breaks in 1.5:

```
Company company = Company.find("id = ?", companyId).first();
```

```
IllegalArgumentException occurred : Unknown parameter position: 1

play.exceptions.JavaExecutionException: Unknown parameter position: 1
	at play.templates.BaseTemplate.throwException(BaseTemplate.java:87)
	at play.templates.GroovyTemplate.internalRender(GroovyTemplate.java:307)
	at play.templates.Template.render(Template.java:28)
	at play.templates.GroovyTemplate.render(GroovyTemplate.java:230)
	at play.mvc.results.RenderTemplate.<init>(RenderTemplate.java:28)
	at play.mvc.Controller.renderTemplate(Controller.java:804)
	at play.mvc.Controller.renderTemplate(Controller.java:782)
	at play.mvc.Controller.render(Controller.java:843)
	at controllers.VirtualOffices.company(VirtualOffices.java:108)
	at play.mvc.ActionInvoker.invokeWithContinuation(ActionInvoker.java:539)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:476)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:470)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:437)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:160)
	at Invocation.HTTP Request(Play!)
Caused by: java.lang.IllegalArgumentException: Unknown parameter position: 1
	at org.hibernate.query.internal.QueryParameterBindingsImpl.getBinding(QueryParameterBindingsImpl.java:240)
	at org.hibernate.query.internal.AbstractProducedQuery.setParameter(AbstractProducedQuery.java:503)
	at org.hibernate.query.internal.AbstractProducedQuery.setParameter(AbstractProducedQuery.java:104)
	at play.db.jpa.JPQL.bindParameters(JPQL.java:229)
	at play.db.jpa.JPQL.find(JPQL.java:79)
	at models.Phone.find(Phone.java)
	at models.CompanyProductSubscription.getTwilioNumber(CompanyProductSubscription.java:342)
	at /app/views/VirtualOffices/company.html.(line:238)
	at play.templates.GroovyTemplate.internalRender(GroovyTemplate.java:282)
	... 13 more
```

Getting similar errors with queries like this too:
```
Phone phone = Phone.find("companyProductSubscription = ?", this).first();
```

**Comment by tahseenarticle** [comment]
Try 
```
Phone phone = Phone.find("companyProductSubscription = ?1", this).first();
```

**Comment by asolntsev** [comment]
@dabeeeenster in Play 1.5, we migrated to Hibernate 5. 
It doesn't allow `id = ?` (question without index) anymore. Now you need to use question marks with indexes: `Company.find("id = ?1 and name = ?2 and type = ?3", companyId)`
