### ISSUE TITLE
Does play 1 support java 9?

### ISSUE THREAD

**Issue by alekseysotnikov** [playframework/play1#1200]

**Comment by asolntsev** [comment]
Hi Aleksei!
I didn't even try yet. I cannot even run unit-tests in my current project
with Java9, so I am skeptical about that.

Did you try to run Play application with Java 9?

Andrei Solntsev

2017-10-22 21:27 GMT+03:00 Aleksei Sotnikov <notifications@github.com>:

**Comment by AlexLaviolette** [comment]
It appears that Play 1 does not currently support Java 9. At the very least, ApplicationCompiler.java will need to be updated to support the new version.

**Comment by tazmaniax** [comment]
I'm getting the following error with continuations on Java 9 which might be related to the above point about ApplicationCompiler and/or JavaFlow...
```
10:26:32,015 [play-thread-1] ERROR ~ 

@75ph95fhb
Internal Server Error (500) for request GET /oauth/callback?state=2&scope=read_write&code=ac_BiBi56NS6A7gcQ7EtYgaCG1SUksAl0AB

await/Continuations error
A await/Continuations error occurred : Cannot use await/continuations when not all application classes on the callstack are properly enhanced. The following class is not enhanced: jdk.internal.reflect.NativeMethodAccessorImpl

play.exceptions.ContinuationsException: Cannot use await/continuations when not all application classes on the callstack are properly enhanced. The following class is not enhanced: jdk.internal.reflect.NativeMethodAccessorImpl
	at play.mvc.Controller.verifyContinuationsEnhancement(Controller.java:1244)
	at play.mvc.Controller.await(Controller.java:1206)
	at controllers.StripeListener.oAuthCallback(StripeListener.java:40)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at play.mvc.ActionInvoker.invokeWithContinuation(ActionInvoker.java:538)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:475)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:469)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:436)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:159)
	at Invocation.HTTP Request(Play!)
```

**Comment by tomparle** [comment]
Hi,

I have the same errors on calls to `await()`, but apart of that, things seem to work properly.

I have this warning on application start with JDK 9, but do not know if this is related : 

> WARNING: Illegal reflective access by javassist.util.proxy.SecurityActions (file:/home/tom/programs/play-1.5.0/framework/lib/javassist-3.21.0-GA.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of javassist.util.proxy.SecurityActions
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations

**Comment by tomparle** [comment]
Since this issue was resolved last year I think it should be closed !
