### ISSUE TITLE
cannot download play press

### ISSUE THREAD

**Issue by maciejwozniak** [playframework/play1#1362]
Hi,  I'm using play framework 1.5.3. 

I haven't been able to download play press module. 
https://www.playframework.com/modules/press-1.0.36.zip

What happened?

**Comment by maciejwozniak** [comment]
also play install press not working. `play install press
~        _            _ 
~  _ __ | | __ _ _  _| |
~ | '_ \| |/ _' | || |_|
~ |  __/|_|\____|\__ (_)
~ |_|            |__/   
~
~ play! 1.5.3, https://www.playframework.com
~
~ Will install press-1.0.36
~ This module is compatible with: *
~ Do you want to install this version (y/n)? y
~ Installing module press-1.0.36...
~
~ Fetching https://www.playframework.com/modules/press-1.0.36.zip
Traceback (most recent call last):
  File "/home/maciej/resources/play-1.5.3/play", line 167, in <module>
    status = cmdloader.commands[play_command].execute(command=play_command, app=play_app, args=remaining_args, env=play_env, cmdloader=cmdloader)
  File "/home/maciej/resources/play-1.5.3/framework/pym/play/commands/modulesrepo.py", line 61, in execute
    install(app, args, env)
  File "/home/maciej/resources/play-1.5.3/framework/pym/play/commands/modulesrepo.py", line 470, in install
    Downloader().retrieve(fetch, archive)
  File "/home/maciej/resources/play-1.5.3/framework/pym/play/commands/modulesrepo.py", line 96, in retrieve
    result = urllib2.urlopen(req)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 404: Not Found
`

repository was moved?

**Comment by Fraserhardy** [comment]
We've noticed the same with other play modules too. Looks like the repo has moved.

**Comment by gregorkistler** [comment]
There is also a thread at the Lightbend forum https://discuss.lightbend.com/t/play-1-x-modules-download-broken/8533

**Comment by ignasi35** [comment]
Thanks all for reporting, we'll track this issue on https://github.com/playframework/playframework.com/issues/442. Please watch that GH issue for updates.

**Comment by ignasi35** [comment]
The modules are back online. Closing.
